server:
  port: ${ec-port}

spring:
  config:
    import: file:${user.home}/.everyCloud/config.yml
  ##db settings
  datasource:
    url: jdbc:sqlite:${user.home}/.everyCloud/EveryCloud.db?${ec-db}
    driver-class-name: org.sqlite.JDBC
  pid:
    file: ${user.home}/.everyCloud/EveryCloud.pid

logging:
  level:
    root: info
    com.project.everycloud.service.mapper: debug

## mybatis
mybatis:
  type-aliases-package: com.project.everycloud.model
  mapper-locations: classpath:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL